# Generated by Django 6.0.3 on 2026-03-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_profile_image_profile_bio_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
