# Generated by Django 6.0.3 on 2026-04-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_studygroup_post_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='warning_count',
            field=models.IntegerField(default=0),
        ),
    ]
